# -*- coding: utf-8 -*-
{
    'name': '(ZRN) Analitica',
    'summary': 'Centro base para hubs, reporteria y analisis de datos de Zoraen',
    'description': """
(ZRN) Analitica
===============

Addon base para la capa analitica:
- hubs ejecutivos y operativos
- reporteria y analisis
- dashboards dinamicos
- procesamiento de datos para metricas
    """,
    'author': 'Zoraen Corporation',
    'website': 'https://www.zoraen.com',
    'category': 'Reporting',
    'version': '0.1.1',
    'license': 'LGPL-3',
    'application': True,
    'depends': ['base', 'web', 'sale', 'stock', 'purchase', 'hr', 'hr_recruitment', 'zrn_commercial'],
    'data': [
        'security/ir.model.access.csv',
        'views/analytics/placeholders/analytics_hub_views.xml',
        'views/analytics/analytics_home_views.xml',
        'views/analytics/placeholders/analytics_overview_views.xml',
        'views/analytics/placeholders/analytics_workspace_views.xml',
        'views/analytics/placeholders/analytics_processing_views.xml',
        'views/analytics/placeholders/analytics_scenarios_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'zrn_analitics/static/lib/echarts/echarts.min.js',
            'zrn_analitics/static/lib/xlsx/xlsx.full.min.js',
            'zrn_analitics/static/lib/alasql/alasql.min.js',
            'zrn_analitics/static/src/js/analytics_processing_utils.js',
            'zrn_analitics/static/src/js/analytics_processing_sources.js',
            'zrn_analitics/static/src/js/analytics_processing_tables.js',
            'zrn_analitics/static/src/js/analytics_processing_view.js',
            'zrn_analitics/static/src/js/dark_mode_bridge.js',
            'zrn_analitics/static/src/js/analytics_form_view.js',
            'zrn_analitics/static/src/js/analytics_hub_action.js',
            'zrn_analitics/static/src/xml/analytics_form_view.xml',
            'zrn_analitics/static/src/xml/analytics_hub_action.xml',
            'zrn_analitics/static/src/xml/hubs/direction/hub.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/shared.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_overview.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_portafolio.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_cobertura.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_canal.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_cliente.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_rfm.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_insights.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_producto.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_tendencias.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_gap.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/tab_bcg.xml',
            'zrn_analitics/static/src/xml/hubs/commercial/hub.xml',
            'zrn_analitics/static/src/xml/hubs/financial/shared.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_overview.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_producto.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_canal.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_marca.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_portafolio.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_precios.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_cartera.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_avanzado.xml',
            'zrn_analitics/static/src/xml/hubs/financial/tab_pnl.xml',
            'zrn_analitics/static/src/xml/hubs/financial/hub.xml',
            'zrn_analitics/static/src/xml/hubs/operations/shared.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_overview.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_demanda.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_abc.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_portafolio.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_tendencias.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_forecast.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_inventarios.xml',
            'zrn_analitics/static/src/xml/hubs/operations/tab_compras.xml',
            'zrn_analitics/static/src/xml/hubs/operations/hub.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/shared.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/tab_overview.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/tab_ranking.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/tab_canales.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/tab_otros.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/tab_alertas.xml',
            'zrn_analitics/static/src/xml/hubs/pdv/hub.xml',
            'zrn_analitics/static/src/xml/hubs/rrhh/tab_overview.xml',
            'zrn_analitics/static/src/xml/hubs/rrhh/tab_predictor.xml',
            'zrn_analitics/static/src/xml/hubs/rrhh/tab_patrones.xml',
            'zrn_analitics/static/src/xml/hubs/rrhh/tab_checklist.xml',
            'zrn_analitics/static/src/xml/hubs/rrhh/tab_historico.xml',
            'zrn_analitics/static/src/xml/hubs/rrhh/hub.xml',
            'zrn_analitics/static/zrn/css/colors.css',
            'zrn_analitics/static/zrn/css/lib.css',
        ],
    },
    'installable': True,
}
